version: '3.7'

services:
  flask:
    build: .
    container_name: flask
    command: 'python main.py'
    ports:
       - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      - pgdbf

  queue:
    build: .
    command: 'python consumer.py'
    depends_on:
      - pgdbf

  pgdbf:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  store: